services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: express_app
    env_file:
      - .env.prod
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - lightformsdevops
      - prometheus-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-admin}
    networks:
      - lightformsdevops
      - prometheus-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - prometheus-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - prometheus-net

networks:
  lightformsdevops:
    external: true
  prometheus-net:
    external: false

volumes:
  grafana_data: {}
