name: Deploy to Developer

on:
  push:
    branches:
      - master   # dispara apenas quando der push na master

jobs:
  deploy:
    runs-on: [self-hosted, Linux, x64, main] # tags do runner
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node (optional, se precisar rodar build no runner)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Exec build script
        env:
          TARGET_DIR: ${{ secrets.TARGET_DIR }}  # ex: /root/express-app
        run: |
          chmod +x $TARGET_DIR/deploy.sh
          sh $TARGET_DIR/deploy.sh
